[[server]]
address  = "ganymede.workbench.network:27018"
protocol = 49
contact  = "contact@workbench.network"

[[server]]
address  = "89.221.220.61:27021"
contact  = "info@goldsrc.one"
protocol = 48
host     = "[GoldSrc.one] CrossPlay (register at discord.goldsrc.one)"
